version: "3.8"
services:
  api:
    build: ./api
    depends_on:
      - db
    volumes: 
            - ./api/:/usr/src/app/
    ports: 
        - 5000:5000
    environment: 
        PORT: 5000
  app :
    container_name: scrape
    build: ./scraper

    depends_on:
      - db
    links:
      - db
    volumes:
      - './:/src'
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbadmin
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local