version: "3.8"
services:
  app :
    container_name: scrape
    build:
      context: ./
    image: scrape
    depends_on:
      - db
    links:
      - db
    volumes:
      - './:/src'
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbadmin
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local